### ISSUE TITLE
Typo in migrate-mirror.ps1

### ISSUE THREAD

**Issue by bcdobbs** [n3wt0n/AzureDevOpsToGitHubRepoMigrator#1]
Really useful script but found the following typo:

Line 41 of migrate-mirror.ps1 currently reads:
`git clone --miror $cloneUrl .`

Should be --mirror.

**Comment by n3wt0n** [comment]
Hey, thanks for the Issue. Good Catch.

I fixed it.

Not sure how it is possible that I had that typo since I've used this script before 😕, probably I've committed an earlier version..

I will re-check the entire codebase to make sure everything is correct.
